[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[[services]]
name = "discord-bot"
command = "python main.py"
healthcheckPath = "/healthz"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[deploy.env]
PYTHON_VERSION = "3.10.11" 