[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[[services]]
name = "discord-bot"
command = "python bot.py"
healthcheckPath = "/healthz"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[[services]]
name = "web-app"
command = "gunicorn web_app:app --bind 0.0.0.0:$PORT"
healthcheckPath = "/healthz"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[deploy.env]
PYTHON_VERSION = "3.10" 